Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MethodMissing: # Let's learn more about this one and enable, soon.
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
